### ISSUE TITLE
Seems not working with graylog 4.3

### ISSUE THREAD

**Issue by qupfer** [Graylog2/docker-compose#13]
Hi, 
I changed in `open-core/docker-compose.yml` the graylog version to 4.3.0.
After that, it doesn't start anymore. 

From the logs
```
open-core-graylog-1 | 2022-06-08 11:23:16,720 INFO : org.graylog2.bootstrap.preflight.MongoDBPreflightCheck - Connected to MongoDB version 5.0.9
open-core-graylog-1 | 2022-06-08 11:23:16,950 INFO : org.graylog2.bootstrap.preflight.SearchDbPreflightCheck - Connected to (Elastic/Open)Search version <Elasticsearch:7.10.2>
open-core-graylog-1 | Exception in thread "main" java.lang.ArithmeticException: / by zero
open-core-graylog-1 |   at org.graylog2.shared.system.stats.fs.OshiFsProbe.lambda$fsStats$11(OshiFsProbe.java:116)
open-core-graylog-1 |   at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
open-core-graylog-1 |   at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
open-core-graylog-1 |   at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)
open-core-graylog-1 |   at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1723)
open-core-graylog-1 |   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
open-core-graylog-1 |   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
open-core-graylog-1 |   at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
open-core-graylog-1 |   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
open-core-graylog-1 |   at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
open-core-graylog-1 |   at org.graylog2.shared.system.stats.fs.OshiFsProbe.fsStats(OshiFsProbe.java:106)
open-core-graylog-1 |   at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.checkJournalDirSizeAndType(DiskJournalPreflightCheck.java:67)
open-core-graylog-1 |   at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.runCheck(DiskJournalPreflightCheck.java:62)
open-core-graylog-1 |   at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
open-core-graylog-1 |   at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51)
open-core-graylog-1 |   at org.graylog2.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:135)
open-core-graylog-1 |   at org.graylog2.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:126)
open-core-graylog-1 |   at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:292)
open-core-graylog-1 |   at org.graylog2.bootstrap.Main.main(Main.java:45)
open-core-graylog-1 exited with code 1

```

Any ideas?
Thanks

**Comment by dennisoelkers** [comment]
Hey @qupfer,

thanks for reporting this. We are already tracking this issue in Graylog2/graylog2-server#12820 and there is a PR fixing it in Graylog2/graylog2-server#12821. Therefore I am closing this issue. Please track the issue/PR to get notified about progress!

**Comment by qupfer** [comment]
Thanks for the quick and helpfull response. :+1:  It get me in the correct direction and found a solution.  
If anybody want a quick workaround, I just add
`GRAYLOG_DISABLE_NATIVE_SYSTEM_STATS_COLLECTOR: "true" ` to the graylog environment and it starts again. 

Thanks again and happy logging :-)
