### ISSUE TITLE
Opensearch is not available after provision certificate

### ISSUE THREAD

**Issue by cuserdzy** [Graylog2/docker-compose#46]
I setup a simple graylog instance via `docker-compose up -d`, but after provision certificate(I skip the last step), the server starts keep error.

The log from "graylog"

```shell
2023-11-30 09:49:04,216 INFO : org.graylog2.security.CustomCAX509TrustManager - CA changed, refreshing trust manager
2023-11-30 09:49:04,222 INFO : org.graylog2.security.CustomCAX509TrustManager - CA changed, refreshing trust manager
2023-11-30 09:49:11,403 INFO : org.graylog2.bootstrap.preflight.PreflightJerseyService - Shutting down HTTP listener at <0.0.0.0:9000>
2023-11-30 09:49:11,409 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.bootstrap.preflight.GraylogCertificateProvisioningPeriodical].
2023-11-30 09:49:11,417 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.events.ClusterEventPeriodical].
2023-11-30 09:49:11,417 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.events.ClusterEventCleanupPeriodical].
2023-11-30 09:49:11,419 INFO : org.glassfish.grizzly.http.server.NetworkListener - Stopped listener bound to [0.0.0.0:9000]
2023-11-30 09:49:11,626 INFO : org.graylog2.plugin.system.FilePersistedNodeIdProvider - Node ID: 13180f69-5c9b-490a-b741-c0b6d27d67e9
2023-11-30 09:49:11,632 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #1
2023-11-30 09:49:16,633 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #2
2023-11-30 09:49:21,633 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #3
2023-11-30 09:49:26,634 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #4
2023-11-30 09:49:31,635 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #5
```

The log from data node
```
2023-11-30T09:44:16.283Z INFO  [Version] HV000001: Hibernate Validator 6.2.5.Final
2023-11-30T09:44:16.713Z INFO  [NetworkListener] Started listener bound to [0.0.0.0:8999]
2023-11-30T09:44:16.715Z INFO  [HttpServer] [HttpServer] Started.
2023-11-30T09:44:16.716Z INFO  [JerseyService] Started REST API at <0.0.0.0:8999>
2023-11-30T09:49:04.468Z INFO  [CustomCAX509TrustManager] CA changed, refreshing trust manager
2023-11-30T09:49:04.469Z INFO  [CustomCAX509TrustManager] CA changed, refreshing trust manager
```

No useful error message

**Comment by janheise** [comment]
@cuserdzy Hi, which step exactly are you skipping? And why?

**Comment by dorokhin** [comment]
The same error:

```
2023-11-30 11:34:19,735 INFO : org.graylog2.bootstrap.preflight.PreflightJerseyService - Shutting down HTTP listener at <0.0.0.0:9000>
2023-11-30 11:34:19,736 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.bootstrap.preflight.GraylogCertificateProvisioningPeriodical].
2023-11-30 11:34:19,737 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.events.ClusterEventPeriodical].
2023-11-30 11:34:19,737 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.events.ClusterEventCleanupPeriodical].
2023-11-30 11:34:19,759 INFO : org.glassfish.grizzly.http.server.NetworkListener - Stopped listener bound to [0.0.0.0:9000]
2023-11-30 11:34:19,999 INFO : org.graylog2.plugin.system.FilePersistedNodeIdProvider - Node ID: 8d98b995-6eac-4aec-ae30-f0598bbd4cac
2023-11-30 11:34:20,007 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #1
2023-11-30 11:34:25,009 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #2
2023-11-30 11:34:30,015 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #3
```

**Comment by janheise** [comment]
At both of you: the error indicates, that no OpenSearch instance is running. 

In the first post, this is also what the snippet from the datanode logs indicate. My question is: which step in the setup did you skip?

@dorokhin : what exactly did you do, up to the error? Did you skip any steps? 

In both cases, I recommend doing a `docker compose down -v`  and then start over from the beginning. Don't skip any setup steps, make sure to press the `resume` button at the end.

If you still get errors, please in any case, add always logs from graylog & the datanode. also, which `docker-compose.yml` are you using? Open? Enterprise? Cluster?

**Comment by cuserdzy** [comment]
Hi @janheise, I used "open-core" file and skipped below step by clicking "Skip provisioning"
![Uploading Snipaste_2023-12-01_10-06-37.png…]()

**Comment by cuserdzy** [comment]
Hi @janheise, I used "open-core" file and skipped below step by clicking "Skip provisioning", then the graylog keep hang.
<img width="1150" alt="Snipaste_2023-12-01_10-06-37" src="https://github.com/Graylog2/docker-compose/assets/30541731/d920e0ce-1107-43fa-bc49-f6131ca5a4de">

I also tried to do "provisioning" but failed as well, shows below error:

graylog node:
```shell
2023-12-01 02:43:30,282 INFO : org.graylog2.security.CustomCAX509TrustManager - CA changed, refreshing trust manager
2023-12-01 02:43:30,286 INFO : org.graylog2.security.CustomCAX509TrustManager - CA changed, refreshing trust manager
2023-12-01 02:43:42,085 INFO : org.graylog2.bootstrap.preflight.GraylogCertificateProvisioningPeriodical - Starting connectivity check with node d6979ccd-2e74-4f9f-949c-61fa38b23723, silencing error messages for 60 seconds.
2023-12-01 02:44:42,242 WARN : org.graylog2.bootstrap.preflight.GraylogCertificateProvisioningPeriodical - Error trying to connect to data node  d6979ccd-2e74-4f9f-949c-61fa38b23723: Failed to connect to 111afc9d1f5f/172.23.0.2:9200, retrying (attempt #21)
```

data node:
```shell
2023-12-01T02:43:30.534Z INFO  [CustomCAX509TrustManager] CA changed, refreshing trust manager
2023-12-01T02:43:30.534Z INFO  [CustomCAX509TrustManager] CA changed, refreshing trust manager
2023-12-01T02:43:39.208Z INFO  [DataNodeConfigurationPeriodical] created CSR for this node
2023-12-01T02:43:40.727Z INFO  [OpensearchSecurityConfiguration] Opensearch transport certificate has following alternative names: 127.0.0.1, localhost, 0:0:0:0:0:0:0:1, 111afc9d1f5f, 0:0:0:0:0:0:0:1, 172.23.0.2
2023-12-01T02:43:40.744Z INFO  [OpensearchSecurityConfiguration] Opensearch HTTP certificate has following alternative names: 127.0.0.1, localhost, 0:0:0:0:0:0:0:1, 111afc9d1f5f, 0:0:0:0:0:0:0:1, 172.23.0.2
2023-12-01T02:43:40.776Z INFO  [TruststoreCreator] Adding certificate transport-chain-CA-root to the truststore
2023-12-01T02:43:40.786Z INFO  [TruststoreCreator] Adding certificate http-chain-CA-root to the truststore
2023-12-01T02:43:40.972Z INFO  [CommandLineProcess] Running process from /usr/share/graylog-datanode/dist/opensearch-2.10.0-linux-aarch64/bin/opensearch
2023-12-01T02:43:41.544Z INFO  [JerseyService] Server configuration changed, restarting Data node REST API to apply security changes
2023-12-01T02:43:41.545Z INFO  [JerseyService] Shutting down HTTP listener at <0.0.0.0:8999>
2023-12-01T02:43:41.574Z INFO  [NetworkListener] Stopped listener bound to [0.0.0.0:8999]
2023-12-01T02:43:41.840Z INFO  [NetworkListener] Started listener bound to [0.0.0.0:8999]
2023-12-01T02:43:41.842Z INFO  [HttpServer] [HttpServer-1] Started.
2023-12-01T02:43:41.842Z INFO  [JerseyService] Started REST API at <0.0.0.0:8999>
2023-12-01T02:43:44.658Z WARN  [OpensearchProcessImpl] Opensearch process failed
org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48) ~[commons-exec-1.3.jar:1.3]
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200) [commons-exec-1.3.jar:1.3]
        at java.lang.Thread.run(Unknown Source) [?:?]
2023-12-01T02:43:44.682Z INFO  [ProcessWatchdog] Detected terminated process, restarting. Attempt #1
2023-12-01T02:43:45.484Z INFO  [CommandLineProcess] Running process from /usr/share/graylog-datanode/dist/opensearch-2.10.0-linux-aarch64/bin/opensearch
2023-12-01T02:43:46.677Z WARN  [OpensearchNodeHeartbeat] Opensearch REST api of process 276 unavailable. Cause: Connection refused
```

**Comment by cuserdzy** [comment]
The error code 137 seems caused by insufficient memory, my machine is t4g.small, 2core, 2g

**Comment by cuserdzy** [comment]
After switch to t4g.medium, 2core, 4g, the opensearch process returns exit code 78 with error "[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]".
Just set map_map_count by "sysctl -w vm.max_map_count=262144", then restart by "docker-compose restart" and re-provisioning, everything works.

<img width="1150" alt="Snipaste_2023-12-01_11-21-55" src="https://github.com/Graylog2/docker-compose/assets/30541731/cb7fd631-e09c-444e-8bc3-11f70059e923">

But which account/password should I use to login?

**Comment by janheise** [comment]
@cuserdzy I'm glad to hear that it works for you! Maybe we should add some info regarding minimal RAM to the docs/readme

**Comment by janheise** [comment]
@dorokhin please post some log files and info on your machine so that I can help you!

**Comment by dorokhin** [comment]
@janheise 
I just tried to run it on my MacBook Pro with 32 gigabytes of RAM.
and everything started successfully.
The virtual machine I previously tried to run had 4 gigabytes of memory, 2 of which were used by another service.
thanks for the help
