### ISSUE TITLE
 OpenSearch/Elasticsearch is not available.

### ISSUE THREAD

**Issue by muhammadsiddiqbe** [Graylog2/docker-compose#48]
```
2023-12-18 10:46:57,642 INFO : org.graylog2.security.CustomCAX509TrustManager - CA changed, refreshing trust manager
2023-12-18 10:47:07,766 INFO : org.graylog2.bootstrap.preflight.PreflightJerseyService - Shutting down HTTP listener at <0.0.0.0:9000>
2023-12-18 10:47:07,773 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.bootstrap.preflight.GraylogCertificateProvisioningPeriodical].
2023-12-18 10:47:07,776 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.events.ClusterEventPeriodical].
2023-12-18 10:47:07,776 INFO : org.graylog2.periodical.Periodicals - Shutting down periodical [org.graylog2.events.ClusterEventCleanupPeriodical].
2023-12-18 10:47:07,788 INFO : org.glassfish.grizzly.http.server.NetworkListener - Stopped listener bound to [0.0.0.0:9000]
2023-12-18 10:47:08,177 INFO : org.graylog2.configuration.IndexerDiscoveryProvider - No indexer hosts configured, using fallback http://127.0.0.1:9200
2023-12-18 10:47:08,242 INFO : org.graylog2.plugin.system.FilePersistedNodeIdProvider - Node ID: 84a7a984-ff52-4d7f-b8ea-6428e00f7fe4
2023-12-18 10:47:08,420 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Failed to connect to /127.0.0.1:9200. - Connection refused.
```

I am getting above error

**Comment by janheise** [comment]
@muhammadsiddiqbe Hi, can you please describe in a little more detail how you ended up with this error?
I can only assume that you started the preflight interface, created a CA (probably also a Renewal policy) and then pressed resume or skip? Did you start a DataNode? Do you even want to use a DataNode or do you want to use a standalone OpenSearch?

**Comment by yodaphone** [comment]
Hi, I'm having the same problem. I used the docker compose file form open-core & when i ran the stack, i'm getting the same error.

i am new to this, so when i started the container and went to x.x.x.x:9000, it begins with the installation. I generate a certificate but it says no nodes configured "No data nodes have been found."

**Comment by janheise** [comment]
@yodaphone Hi, you have a different error - which is also, what the message says. May I point you to the docs? 

https://go2docs.graylog.org/5-2/setting_up_graylog/graylog_data_node_getting_started.htm?tocpath=Setting%20up%20Graylog%7CGraylog%20Data%20Node%7C_____1
and/or
https://github.com/Graylog2/docker-compose?tab=readme-ov-file#configure-your-os

OpenSearch is included in the DataNode. To fix it, easiest is to start over by doing `docker compose down -v` to remove everything and start over after fixing the os-setting. Let me know if it works!

**Comment by yodaphone** [comment]
i started over and ran the docker compose file in open-core with the env file again. I did change the setting in the OS but still getting this error. I'm running 
Ubuntu 22.04
Docker version 24.07

`2023-12-20 14:04:37,840 INFO : org.graylog2.featureflag.ImmutableFeatureFlagsCollector - Following feature flags are used: {default properties file=[frontend_hotkeys=on, field_types_management=on, cloud_inputs=on, scripting_api_preview=>
2023-12-20 14:04:40,158 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: AWS plugins 5.2.2+8eab621 [org.graylog.aws.AWSPlugin]
2023-12-20 14:04:40,167 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Integrations 5.2.2+8eab621 [org.graylog.integrations.IntegrationsPlugin]
2023-12-20 14:04:40,170 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Threat Intelligence Plugin 5.2.2+8eab621 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2023-12-20 14:04:40,173 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Elasticsearch 7 Support 5.2.2+8eab621 [org.graylog.storage.elasticsearch7.Elasticsearch7Plugin]
2023-12-20 14:04:40,176 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: OpenSearch 2 Support 5.2.2+8eab621 [org.graylog.storage.opensearch2.OpenSearch2Plugin]
2023-12-20 14:04:40,309 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Dlog4j2.formatMsgNoLookups=true -Djdk.tls.acknowledgeCloseNotify=true -XX:+UnlockExperimentalVMOptions -XX:-OmitStackTraceInFastThrow -XX:+>
2023-12-20 14:04:41,277 INFO : org.mongodb.driver.client - MongoClient with metadata {"driver": {"name": "mongo-java-driver|legacy", "version": "4.8.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "6.2.>
2023-12-20 14:04:41,299 INFO : org.mongodb.driver.client - MongoClient with metadata {"driver": {"name": "mongo-java-driver|legacy", "version": "4.8.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "6.2.>
2023-12-20 14:04:41,268 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:73) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198) [graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?]
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:107) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:82) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68) ~[graylog.jar:?]
        ... 4 more
2023-12-20 14:04:41,385 INFO : org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
2023-12-20 14:05:11,414 INFO : org.graylog2.bootstrap.preflight.MongoDBPreflightCheck - MongoDB is not available. Retry #1
2023-12-20 14:05:13,449 INFO : org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
2023-12-20 14:05:13,986 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketException: mongodb: Temporary failure in name resolution
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:217) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:78) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198) [graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: mongodb: Temporary failure in name resolution
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(Unknown Source) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:209) ~[graylog.jar:?]
        ... 6 more
2023-12-20 14:05:14,496 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketException: mongodb
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:217) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:78) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198) [graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: mongodb
        at java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:209) ~[graylog.jar:?]
        ... 6 more
2023-12-20 14:05:24,049 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketException: mongodb: Temporary failure in name resolution
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:217) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:78) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198) [graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: mongodb: Temporary failure in name resolution
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(Unknown Source) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:209) ~[graylog.jar:?]
        ... 6 more
2023-12-20 14:05:24,559 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketException: mongodb
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:217) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:78) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198) [graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: mongodb
        at java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:209) ~[graylog.jar:?]
        ... 6 more
2023-12-20 14:05:34,107 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketException: mongodb: Temporary failure in name resolution
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:217) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:78) ~[graylog.jar:?]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68) ~[graylog.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:183) ~[graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:198) [graylog.jar:?]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:158) [graylog.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
`

**Comment by janheise** [comment]
@yodaphone interesting, I never got this one myself. That looks as if mongodb never came up. You never get to the UI then, right? please do a `docker compose down -v` again, and then start mongodb first with `docker compose up -d mongodb` make sure that it's running ok. If it's up, start the rest of the services. I'm re-checking that file myself again, too.

**Comment by yodaphone** [comment]
hi there
here's the log from the mongodb container

`WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814`

whats wierd is that i have another docker instance running in a different VM that is identical to the one thats running this instance as well and I dont have that error there.

**Comment by yodaphone** [comment]
Ok, I figured out the issue. the only difference between the VMs was that i was using KVM for the processor but when i changed it to "host" mongodb started working. not sure why this is having an impact. I use proxmox for Virtualization

**Comment by janheise** [comment]
@yodaphone I'm glad you found the problem! So everything works now?

**Comment by janheise** [comment]
closed this as there was no further feedback so I guess it works now
