### ISSUE TITLE
The graylog/graylog-datanode:5.2 docker image is not starting correctly returning an error max_map_count value should be at least 262144 but is 65530

### ISSUE THREAD

**Issue by djaparidze** [Graylog2/docker-compose#53]
When starting docker compose image from open-core/docker-compose.yml, it runs graylog-datanode:5.2, which is not starting correctly due to error:

2024-01-06T19:47:45.674Z ERROR [PreflightCheckService] Preflight check failed with error: /proc/sys/vm/max_map_count value should be at least 262144 but is 65530 (set via "vm.max_map_count" sysctl)
2024-01-06T19:47:45.674Z ERROR [CmdLineTool] Startup error:
org.graylog2.bootstrap.preflight.PreflightCheckException: /proc/sys/vm/max_map_count value should be at least 262144 but is 65530 (set via "vm.max_map_count" sysctl)
	at org.graylog.datanode.bootstrap.preflight.OpenSearchPreconditionsCheck.runCheck(OpenSearchPreconditionsCheck.java:51) ~[graylog-datanode.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
	at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51) ~[graylog2-server-5.2.3.jar:?]
	at org.graylog.datanode.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:133) ~[graylog-datanode.jar:?]
	at org.graylog.datanode.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:118) ~[graylog-datanode.jar:?]
	at org.graylog.datanode.bootstrap.CmdLineTool.doRun(CmdLineTool.java:286) ~[graylog-datanode.jar:?]
	at org.graylog.datanode.bootstrap.CmdLineTool.run(CmdLineTool.java:244) [graylog-datanode.jar:?]
	at org.graylog.datanode.bootstrap.Main.main(Main.java:57) [graylog-datanode.jar:?]
Exception in thread "main" org.graylog2.bootstrap.preflight.PreflightCheckException: /proc/sys/vm/max_map_count value should be at least 262144 but is 65530 (set via "vm.max_map_count" sysctl)
	at org.graylog.datanode.bootstrap.preflight.OpenSearchPreconditionsCheck.runCheck(OpenSearchPreconditionsCheck.java:51)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51)
	at org.graylog.datanode.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:133)
	at org.graylog.datanode.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:118)
	at org.graylog.datanode.bootstrap.CmdLineTool.doRun(CmdLineTool.java:286)
	at org.graylog.datanode.bootstrap.CmdLineTool.run(CmdLineTool.java:244)
	at org.graylog.datanode.bootstrap.Main.main(Main.java:57)

**Comment by janheise** [comment]
Hi, @djaparidze please configure docker/your OS to use the correct setting as written here: https://go2docs.graylog.org/5-2/setting_up_graylog/graylog_data_node_getting_started.htm?tocpath=Setting%20up%20Graylog%7CGraylog%20Data%20Node%7C_____1 

You'll probably want to start over after doing that by issuing `docker compose down -v` 

Please let me know if it works for you!

**Comment by janheise** [comment]
the OP did not come back to this issue but I guess it's fixed now because the solution works for other users.
