### ISSUE TITLE
Facing error org.graylog2.bootstrap.CmdLineTool - Startup error

### ISSUE THREAD

**Issue by raynent** [Graylog2/docker-compose#62]
1st ERROR
graylog-datanode-1  | ERROR StatusConsoleListener Deprecated log4j.xml setting detected <bufferSize="500"> Using default <bufferSizeBytes=50MB> instead
![image](https://github.com/Graylog2/docker-compose/assets/143066456/03ee0386-21d9-48e9-ac52-dc1dd6692876)

2nd ERROR
graylog-graylog-1   | 2024-02-14 07:06:38,530 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
graylog-graylog-1   | com.google.inject.CreationException: Unable to create injector, see the following errors:
graylog-graylog-1   |
graylog-graylog-1   | 1) [Guice/ErrorInCustomProvider]: IllegalStateException: No Datanode available, terminating.
graylog-graylog-1   |   while locating IndexerDiscoveryProvider
graylog-graylog-1   |   at IndexerDiscoveryModule.configure(IndexerDiscoveryModule.java:34)
graylog-graylog-1   |   while locating List<URI> annotated with interface IndexerHosts
graylog-graylog-1   |
graylog-graylog-1   | Learn more:
graylog-graylog-1   |   https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
graylog-graylog-1   |
graylog-graylog-1   | 1 error
graylog-graylog-1   |
graylog-graylog-1   | ======================
graylog-graylog-1   | Full classname legend:
graylog-graylog-1   | ======================
graylog-graylog-1   | IndexerDiscoveryModule:   "org.graylog2.configuration.IndexerDiscoveryModule"
graylog-graylog-1   | IndexerDiscoveryProvider: "org.graylog2.configuration.IndexerDiscoveryProvider"
graylog-graylog-1   | IndexerHosts:             "org.graylog2.configuration.IndexerHosts"
graylog-graylog-1   | URI:                      "java.net.URI"
graylog-graylog-1   | ========================
graylog-graylog-1   | End of classname legend:
graylog-graylog-1   | ========================
graylog-graylog-1   |
graylog-graylog-1   |   at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.Guice.createInjector(Guice.java:87) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.Guice.createInjector(Guice.java:69) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.Guice.createInjector(Guice.java:59) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.ServerBootstrap.getPreflightInjector(ServerBootstrap.java:269) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.ServerBootstrap.runPreflightWeb(ServerBootstrap.java:180) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:164) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:148) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:308) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.bootstrap.Main.main(Main.java:55) [graylog.jar:?]
graylog-graylog-1   | Caused by: java.lang.IllegalStateException: No Datanode available, terminating.
graylog-graylog-1   |   at org.graylog2.configuration.IndexerDiscoveryProvider.doGet(IndexerDiscoveryProvider.java:82) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.configuration.IndexerDiscoveryProvider.get(IndexerDiscoveryProvider.java:63) ~[graylog.jar:?]
graylog-graylog-1   |   at org.graylog2.configuration.IndexerDiscoveryProvider.get(IndexerDiscoveryProvider.java:38) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213) ~[graylog.jar:?]
graylog-graylog-1   |   at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186) ~[graylog.jar:?]
graylog-graylog-1   |   ... 11 more
![image](https://github.com/Graylog2/docker-compose/assets/143066456/697639b7-3d39-49a3-b521-71a7dfe60466)

![image](https://github.com/Graylog2/docker-compose/assets/143066456/ee0dba6e-ea0c-4323-9b4c-c160853f04ae)

3rd ERROR

graylog-graylog-1   | 2024-02-14 07:06:40,593 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #1
graylog-graylog-1   | 2024-02-14 07:06:45,593 INFO : org.graylog2.storage.versionprobe.VersionProbe - OpenSearch/Elasticsearch is not available. Retry #2
![image](https://github.com/Graylog2/docker-compose/assets/143066456/e9069151-c676-4094-9271-4e6bb852a9c3)

**Comment by raynent** [comment]
have found the solution ,

docker volume ls

clean old volume 
docker volume rm <volume_name>

docker volume rm graylog_es_data graylog_graylog-datanode graylog_graylog_data graylog_graylog_journal graylog_mongo_data graylog_mongodb_data

vim /etc/sysctl.conf

vm.max_map_count=262144

rebuild container will be ok
