### ISSUE TITLE
docker compse max_map_count value should be at least 262144 but is 65530

### ISSUE THREAD

**Issue by nicehyukiv** [Graylog2/docker-compose#65]
version: "3.8"

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "./mongodb_data:/data/db"
    restart: "on-failure"

  datanode:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:5.2}"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
        #- "sysctl.conf:/etc/sysctl.conf"
        #restart: "on-failure"
    restart: "always"
    command: "sysctl -w vm.max_map_count=262144"
      #command: "sysctl -p"
      #user: "root"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.2}"
    depends_on:
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://xxx.xxx.xx.xx:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "5140:5140/udp"   # Syslog
    - "5140:5140/tcp"   # Syslog
    - "5555:5555/tcp"   # RAW TCP
    - "5555:5555/udp"   # RAW TCP
    - "9000:9000/tcp"   # Server API
    - "12201:12201/tcp" # GELF TCP
    - "12201:12201/udp" # GELF UDP
    #- "10000:10000/tcp" # Custom TCP port
    #- "10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
    mongodb_data:
    graylog-datanode:
    graylog_data:

------------------------docker compose up----------------------------------------------

datanode-1  | 2024-03-17T13:01:00.157Z ERROR [PreflightCheckService] Preflight check failed with error: /proc/sys/vm/max_map_count value should be at least 262144 but is 65530 (set via "vm.max_map_count" sysctl)
datanode-1  | 2024-03-17T13:01:00.157Z ERROR [CmdLineTool] Startup error:
datanode-1  | org.graylog2.bootstrap.preflight.PreflightCheckException: /proc/sys/vm/max_map_count value should be at least 262144 but is 65530 (set via "vm.max_map_count" sysctl)
datanode-1  |   at org.graylog.datanode.bootstrap.preflight.OpenSearchPreconditionsCheck.runCheck(OpenSearchPreconditionsCheck.java:51) ~[graylog-datanode.jar:?]
datanode-1  |   at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
datanode-1  |   at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51) ~[graylog2-server-5.2.5.jar:?]
datanode-1  |   at org.graylog.datanode.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:133) ~[graylog-datanode.jar:?]
datanode-1  |   at org.graylog.datanode.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:118) ~[graylog-datanode.jar:?]
datanode-1  |   at org.graylog.datanode.bootstrap.CmdLineTool.doRun(CmdLineTool.java:286) ~[graylog-datanode.jar:?]
datanode-1  |   at org.graylog.datanode.bootstrap.CmdLineTool.run(CmdLineTool.java:244) [graylog-datanode.jar:?]
datanode-1  |   at org.graylog.datanode.bootstrap.Main.main(Main.java:57) [graylog-datanode.jar:?]
datanode-1  | Exception in thread "main" org.graylog2.bootstrap.preflight.PreflightCheckException: /proc/sys/vm/max_map_count value should be at least 262144 but is 65530 (set via "vm.max_map_count" sysctl)
datanode-1  |   at org.graylog.datanode.bootstrap.preflight.OpenSearchPreconditionsCheck.runCheck(OpenSearchPreconditionsCheck.java:51)
datanode-1  |   at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
datanode-1  |   at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51)
datanode-1  |   at org.graylog.datanode.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:133)
datanode-1  |   at org.graylog.datanode.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:118)
datanode-1  |   at org.graylog.datanode.bootstrap.CmdLineTool.doRun(CmdLineTool.java:286)
datanode-1  |   at org.graylog.datanode.bootstrap.CmdLineTool.run(CmdLineTool.java:244)
datanode-1  |   at org.graylog.datanode.bootstrap.Main.main(Main.java:57)
datanode-1 exited with code 0
datanode-1  | ERROR StatusConsoleListener Deprecated log4j.xml setting detected <bufferSize="500"> Using default <bufferSizeBytes=50MB> instead
datanode-1  | 2024-03-17T13:01:02.190Z INFO  [ImmutableFeatureFlagsCollector] Following feature flags are used: {}

-------------------------------------------docker-compose.yml add command---------------------------------------------------

command: "sysctl -w vm.max_map_count=262144"

datanode-1  | sysctl: setting key "vm.max_map_count", ignoring: Read-only file system
datanode-1  | sysctl: setting key "vm.max_map_count", ignoring: Read-only file system
datanode-1  | sysctl: setting key "vm.max_map_count", ignoring: Read-only file system
datanode-1  | sysctl: setting key "vm.max_map_count", ignoring: Read-only file system
datanode-1  | sysctl: setting key "vm.max_map_count", ignoring: Read-only file system

--------------------------------------------docker build--------------------------------------------------
Dockerfile 

FROM graylog/graylog-datanode:5.2

RUN sysctl -w vm.max_map_count=262144

docker build -t graylog/graylog-datanode:5.2.new .

--------------------------------------------------------------------------------------------
The above error has not been resolved.

**Comment by nicehyukiv** [comment]
On the host machine 
sysctl -w vm.max_map_count=262144 setting on the host machine.
Remember that you are not adding it to the docker
