### ISSUE TITLE
no connect mongo db

### ISSUE THREAD

**Issue by ilusha0561** [Graylog2/docker-compose#73]
2024-09-12 10:16:20,418 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongodb:27017
com.mongodb.MongoSocketException: mongodb
	at com.mongodb.internal.connection.ServerAddressHelper.getSocketAddresses(ServerAddressHelper.java:59) ~[graylog.jar:?]
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:101) ~[graylog.jar:?]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:80) ~[graylog.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:201) ~[graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:193) [graylog.jar:?]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:153) [graylog.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.UnknownHostException: mongodb
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
	at com.mongodb.internal.connection.DefaultInetAddressResolver.lookupByName(DefaultInetAddressResolver.java:34) ~[graylog.jar:?]
	at com.mongodb.internal.connection.ServerAddressHelper.getSocketAddresses(ServerAddressHelper.java:55) ~[graylog.jar:?]
	... 6 more
2024-09-12 10:16:32,865 INFO : org.graylog2.bootstrap.preflight.MongoDBPreflightCheck - MongoDB is not available. Retry #12

**Comment by sethgraylog** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this looks like you need support. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
