### ISSUE TITLE
Elasticsearch nodes disk usage above high watermark 

### ISSUE THREAD

**Issue by fredrikjag** [Graylog2/docker-compose#77]
This issue appears as soon as I start my docker instances.

Log from the datanode
```
2024-10-09T09:13:26.607Z INFO  [OpensearchProcessImpl] [2024-10-09T09:13:26,607][WARN ][o.o.c.r.a.DiskThresholdMonitor] [datanode] high disk watermark [90%] exceeded on [5ii93UqvQoC-Vnxt6Fx28g][datanode][/var/lib/graylog-datanode/opensearch/data/nodes/0] free: 4.1gb[8.6%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete

{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [.ds-gl-datanode-metrics-000003] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"}],"type":"cluster_block_exception","reason":"index [.ds-gl-datanode-metrics-000003] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"},"status":429}
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.convertResponse(RestClient.java:376) ~[graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.access$1800(RestClient.java:120) ~[graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient$1.completed(RestClient.java:426) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient$1.completed(RestClient.java:422) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:182) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [graylog-storage-opensearch2-6.0.7.jar:?]
                at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

Just as a test, I logged on to the shell of datanode and created 6.3GB file with /dev/random.

![image](https://github.com/user-attachments/assets/e15069ac-6d27-4f4e-b9e1-ec1e027b4980)

Testing the docker-compose file I've used on another machine does not yield this same issue. 
I would let this go and just use that machine, but I am afraid I am just kicking this issue forward to future me.

The compose-file I am using
```
version: "3.8"

# For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
# Please take a look at the README at the top of this repo or the regular docs for more info.

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  # For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
  # Please take a look at the README at the top of this repo or the regular docs for more info.
  datanode:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:6.0.7}"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:8999:8999/tcp"   # DataNode API
      - "127.0.0.1:9200:9200/tcp"
      - "127.0.0.1:9300:9300/tcp"
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:6.0.7}"
    depends_on:
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "127.0.0.1:5044:5044/tcp"   # Beats
    - "127.0.0.1:5140:5140/udp"   # Syslog
    - "127.0.0.1:5140:5140/tcp"   # Syslog
    - "127.0.0.1:5555:5555/tcp"   # RAW TCP
    - "127.0.0.1:5555:5555/udp"   # RAW UDP
    - "127.0.0.1:9000:9000/tcp"   # Server API
    - "127.0.0.1:12201:12201/tcp" # GELF TCP
    - "127.0.0.1:12201:12201/udp" # GELF UDP
    #- "127.0.0.1:10000:10000/tcp" # Custom TCP port
    #- "127.0.0.1:10000:10000/udp" # Custom UDP port
    - "127.0.0.1:13301:13301/tcp" # Forwarder data
    - "127.0.0.1:13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
  mongodb_data:
  graylog-datanode:
  graylog_data:
  graylog_journal:
```

The available storage on the host machine.

![image](https://github.com/user-attachments/assets/5b375086-6790-44b9-8360-f0993f223060)

Docker host system info and storage

![image](https://github.com/user-attachments/assets/9ec55b15-977f-44af-8504-0a8ee3a9dcac)

**Comment by sethgraylog** [comment]
HI [fredrikjag](https://github.com/fredrikjag)! We are using GitHub issues for tracking bugs in Graylog itself, but this looks like a support question. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!

**Comment by fredrikjag** [comment]
> HI [fredrikjag](https://github.com/fredrikjag)! We are using GitHub issues for tracking bugs in Graylog itself, but this looks like a support question. Please post this issue to our [discussion forum](https://community.graylog.org/).
> 
> Thank you!

I don't really think this is only a support question.
This must be a bug, how can starting the containers and completing the initial setup cause the application to 7 days later, crash?

I have not put any data on the graylog instance at all.

Now, restarting the instances it will result in application traceback.. 

```
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [.ds-gl-datanode-metrics-000003] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"}],"type":"cluster_block_exception","reason":"index [.ds-gl-datanode-metrics-000003] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"},"status":429}
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.convertResponse(RestClient.java:376) ~[graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient.access$1800(RestClient.java:120) ~[graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient$1.completed(RestClient.java:426) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.opensearch.client.RestClient$1.completed(RestClient.java:422) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:182) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [graylog-storage-opensearch2-6.0.7.jar:?]
                at org.graylog.shaded.opensearch2.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [graylog-storage-opensearch2-6.0.7.jar:?]
                at java.base/java.lang.Thread.run(Unknown Source) [?:?]

**Comment by drewmiranda-gl** [comment]
Hi @fredrikjag adding to Jan above, if you believe this is a bug, can you share the series of steps you took that led you to this state?

Can you also confirm if your disk did indeed exceed the [default watermark](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/cluster-settings/) of 85% disk space used?

Can you also share the output of the following which specifically looks for a log line:
Be sure to replace `docker-datanode-1` with your datanode container name or container id
`sudo docker logs docker-datanode-1 2> /dev/null | grep "space"`

should output something like:
```
10-30T16:13:24.116Z INFO  [OpensearchProcessImpl] [2024-10-30T16:13:24,116][INFO ][o.o.e.NodeEnvironment    ] [datanode] using [1] data paths, mounts [[/var/lib/graylog-datanode (/dev/mapper/ubuntu--vg-ubuntu--lv)]], net usable_space [18.1gb], net total_space [29.3gb], types [ext4]
```

What state is your graylog and data node in now? Do they start? Are they reachable via their bound ports?

Thanks!

**Comment by fredrikjag** [comment]
****

> Hi @fredrikjag adding to Jan above, if you believe this is a bug, can you share the series of steps you took that led you to this state?
> 
> Can you also confirm if your disk did indeed exceed the [default watermark](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/cluster-settings/) of 85% disk space used?
> 
> Can you also share the output of the following which specifically looks for a log line: Be sure to replace `docker-datanode-1` with your datanode container name or container id `sudo docker logs docker-datanode-1 2> /dev/null | grep "space"`
> 
> should output something like:
> 
> ```
> 10-30T16:13:24.116Z INFO  [OpensearchProcessImpl] [2024-10-30T16:13:24,116][INFO ][o.o.e.NodeEnvironment    ] [datanode] using [1] data paths, mounts [[/var/lib/graylog-datanode (/dev/mapper/ubuntu--vg-ubuntu--lv)]], net usable_space [18.1gb], net total_space [29.3gb], types [ext4]
> ```
> 
> What state is your graylog and data node in now? Do they start? Are they reachable via their bound ports?
> 
> Thanks!

At the moment it's working as I tried re-created the environment.
Currently there is no watermark, but give it a couple of days and we are back at square one.

This is the output.
```
2024-10-31T09:12:31.556Z INFO  [OpensearchProcessImpl] [2024-10-31T09:12:31,556][INFO ][o.o.e.NodeEnvironment    ] [datanode] using [1] data paths, mounts [[/var/lib/graylog-datanode (/dev/mapper/ubuntu--vg-ubuntu--lv)]], net usable_space [73.1gb], net total_space [97.8gb], types [ext4]```
